### ISSUE TITLE
Intermittent connectivity issues from node app in kubernetes sidecar deployment

### ISSUE THREAD

**Issue by rigratz** [GoogleCloudPlatform/cloud-sql-proxy#1316] opened 2022-08-17 22:30 UTC
Hello, I've been attempting to run down a connectivity issue with a handful of different Google reps, and they suggested I create an issue here so that it can be tracked easily.

## Bug Description
I have two kubernetes applications running on GKE v1.22 that connects to a cloud SQL db using a Kubernetes sidecar container as described in Google's documentation. One of these applications works fine. The other one however, runs into an issue roughly every 24 hours where connectivity is temporarily lost, as the logs appear to show the Cloud SQL Auth Proxy throwing an error and restarting. The error message logged is extremely vague so I'm not sure entirely what is at fault, but it is very interesting that this is only impacting one of the services even though their sidecar configurations are identical. During the time that the proxy is restarting, the application is down and unable to handle requests, which is obviously a big problem.

## Example code (or command)
Pods are being managed as part of `Deployment` resources, and the relevant configuration looks something like this (irrelevant details omitted). This configuration was done in accordance with the documentation and sample apps described here: https://cloud.google.com/sql/docs/sqlserver/connect-kubernetes-engine#run_the_as_a_sidecar:

```
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      containers:
      - command:
        - /cloud_sql_proxy
        - -instances=REDACTED=tcp:1433
        image: gcr.io/cloudsql-docker/gce-proxy:1.31.0
        imagePullPolicy: IfNotPresent
        name: cloud-sql-proxy
        resources: {}
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - envFrom:
        - secretRef:
            name: REDACTED # Credentials to the DB come from here
        image: REDACTED
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: REDACTED
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: REDACTED
      serviceAccountName: REDACTED
      terminationGracePeriodSeconds: 30
```

## Stacktrace
Logs from Cloud SQL proxy, which correlate with logs from our service being unable to connect to sql, and the proxy then restarting:
```
Get "https://sqladmin.googleapis.com/sql/v1beta4/projects/OUR-SQL-INSTANCE/connectSettings?alt=json&prettyPrint=false": dial tcp: lookup sqladmin.googleapis.com on 10.3.240.10:53: read udp 10.0.15.4:45428->10.3.240.10:53: read: connection refused

errors parsing config:
```
...without information on what config was wrong or why (NOTE: those IPs are not our databse, but I assume you'll know what they are)

## How to reproduce

  1. We deploy our application using a Helm chart and FluxCD. This creates the deployments which spin up the pods
  2. Monitor logs and ~24 hours apart from each other there will be daily disconnection errors (FWIW this has currently been happening around 530 AM PST)

## Environment

1. OS type and version: Base docker image is node:14-alpine (Alpine Linux)
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): gcr.io/cloudsql-docker/gce-proxy:1.31.0

**Comment by enocom** [comment] 2022-08-17 23:12
Connection reset by peer errors indicate there's a network problem. Are you running a service mesh like Istio?

**Comment by kurtisvg** [comment] 2022-08-18 03:41
This exception looks like it's a bit misleading - it's not an error with the config itself, but an error that occurred while the config was being parsed. It's being thrown from [here](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/480992a7671abe9b76f940175f4ed17f5271d3f8/cmd/cloud_sql_proxy/proxy.go#L328), which from the looks of it is being returned from the API call that happens [here](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/480992a7671abe9b76f940175f4ed17f5271d3f8/cmd/cloud_sql_proxy/proxy.go#L267). 

From the message, it's failing when trying to resolve the dns name "sqladmin.googleapis.com" (`read: connection refused`). This indicates that something is denying it's attempts to resolve the DNS name. 

[K8s has a page on debugging DNS failures](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues). Would you mind taking a look and see if any of the steps help diagnose? Given the ~24h reourrence, I'd maybe look at this [Known Issue](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues) where the resolv.conf is being replaced.  

It would also be great if you can provide more logs around when the proxy encounters the error. Does it continue to fail or does it recover after some time? Do you always have to restart it?

**Comment by enocom** [comment] 2022-08-24 19:02
Have you tried to reproduce this on a fresh cluster?

The error message makes it clear that the DNS lookup is failing:

```
lookup sqladmin.googleapis.com on 10.3.240.10:53: read udp 10.0.15.4:45428->10.3.240.10:53: read: connection refused
```

`10.3.240.10:53` is the DNS server that the process is using. For whatever reason the DNS server isn't responding.

**Comment by enocom** [comment] 2022-09-14 14:05
I’m going to close this since it’s been sitting for awhile. Feel free to re-open with more information.

**Closed by enocom** 2022-09-14 14:05 UTC
Labels: priority: p2, type: question
