### ISSUE TITLE
Inconsistent behaviour when specifying an instance that does not exist

### ISSUE THREAD

**Issue by JamesMcNee** [GoogleCloudPlatform/cloud-sql-proxy#1765] opened 2023-04-21 14:11 UTC
### Bug Description

There is some inconsistent behaviour when starting a proxy and connecting to an instance that does not exist.

If the `--port` flag is omitted, an error message will inform the user that the instance they are trying to connect to does not exist and the proxy process will terminate, if however a port is specified connection will appear to have been successful, but on the first attempt at connecting (e.g. via a database client) an error message will appear; however the process will remain active.

In the second scenario the `/readiness` endpoint will also show the error about the instance not existing.

### Example code (or command)

```
cloud-sql-proxy project:region:some-fake-instance --auto-iam-authn --address 0.0.0.0 --port 12345
```

### Stacktrace

```bash
2023/04/21 14:26:32 Authorizing with Application Default Credentials
2023/04/21 14:26:32 [projectregion:some-fake-instance] Listening on [::]:12345
2023/04/21 14:26:32 The proxy has started successfully and is ready for new connections!
```
```


### Steps to reproduce?

1. Start a proxy pointing at an instance that does not exist and specify a port explicitly 
2. Observe the process remains active and no error is reported
3. Start a proxy pointing at an instance that does not exist and omit specifying a port
4. Observe the process is terminated and an error reported
...


### Environment

1. OSX and Linux show the same behaviour
2. cloud-sql-proxy version 2.2.0+darwin.arm64


### Additional Details

_No response_

**Comment by jackwotherspoon** [comment] 2023-04-21 14:20
Hi @JamesMcNee! 

Thanks for raising an issue on the Cloud SQL Proxy! 😄 

I will look to reproduce the issue and provide a fix so we make sure the behaviour is consistent with the default port or a provided port! I will provide updates here with progress or if I require additional details from you.

Have a great day! 😃

**Comment by JamesMcNee** [comment] 2023-04-21 14:24
Hi @jackwotherspoon, thanks for the super speedy response!

Let me know if you need anything else from me, have a good weekend 👍

**Comment by enocom** [comment] 2023-04-21 22:48
This is actually working as intended. When no port is specified, the Proxy tries to use a database-native port (5432 for Postgres, 3306 for MySQL, etc). To do that, it makes an API call to find the engine type. Because this introduces some latency into the startup, we recommend using `--port` in production environments to prevent this initial call. The Proxy then won't attempt to connect until a client attempts to connect to the database.

It's possible #348 is what you're looking for. In that issue, we'd add a flag such that the Proxy would attempt to connect to an instance and die if it couldn't.

Would you mind elaborating on what you're trying to do with these non-existent instances?

**Comment by JamesMcNee** [comment] 2023-04-22 05:22
Hi @enocom,

Thanks for the explanation. 

In terms of what we are doing with the nonexistent instances... nothing! Essentially we provide a wrapper CLI for all of our platform capability to our developers, one of these is to start a database proxy. We will infer the correct instance name to connect to from the current project the developer has open, but we also allow the developer to override this by specifying a flag.

Previously we had been using v1 of the proxy, and when upgrading to V2, I noticed this change of behaviour; in v1 the error is optimistically presented.

I believe having a flag, as described in the issue that you linked, would satisfy our use case.

Given that when enabling the health-check endpoints the readiness endpoint does show that the instance doesn't exist, I am assuming this does cause the connection. Could an alternative be to have the proxy process end after its determined the instance doesn't exist?

**Comment by enocom** [comment] 2023-04-22 12:50
Out of curiosity how were you invoking v1?

**Comment by JamesMcNee** [comment] 2023-04-22 13:10
We were using the `-instances` flag and specifying the `=tcp` arg e.g. translating the command from the original issue back

`cloud_sql_proxy -instances=project:region:some-fake-instance=tcp:0.0.0.0:5432 -enable_iam_login`

**Comment by enocom** [comment] 2023-05-04 15:38
Going to close this as a duplicate of #348 in the meantime.

**Closed by enocom** 2023-05-04 15:38 UTC
Labels: priority: p2, type: question
