### ISSUE TITLE
Port binding fails silently on macOS 13.1

### ISSUE THREAD

**Issue by joseph-maddox** [GoogleCloudPlatform/cloud-sql-proxy#1698] opened 2023-03-14 21:36 UTC
### Bug Description

When the TCP port (e.g. 3306) is already in use (in my case by an unrelated Docker container) there is nothing in the output of the cloud_sql_proxy to suggest that anything is amiss. This led to quite a bit of confusion until I finally realized what was going on.

### Example code (or command)

```
cloud_sql_proxy -instances=my-gcp-proxy:us-central1:my-instance-name=tcp:3306 -credential_file my-key-filejson
```

### Stacktrace

```bash
2023/03/14 14:27:47 current FDs rlimit set to 245760, wanted limit is 8500. Nothing to do here.
2023/03/14 14:27:47 using credential file for authentication; email=service-account@my-cp-project.iam.gserviceaccount.com
2023/03/14 14:27:47 Listening on 127.0.0.1:3306 for my-gcp-proxy:us-central1:my-instance-name
2023/03/14 14:27:47 Ready for new connections
2023/03/14 14:27:47 Generated RSA key in 67.019489ms
```
```


### Steps to reproduce?

1. Have another process bind to port 3306 (in my case an unrelated Docker container)
2. Start the cloud_sql_proxy and tell it to use the same port
3. Observe that no error is present in the logs
4. Think that you're talking on 3306 to your Cloud SQL instance
5. Realize that you aren't... you're connected to whatever previously had 3306 (in my case a random Docker container)

### Environment

1. OS type and version: macOS 13.1 (build 22C65)
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 1.33.2+darwin.amd64
3. Proxy invocation command: cloud_sql_proxy -instances=my-gcp-proxy:us-central1:my-instance-name=tcp:3306 -credential_file my-key-filejson


### Additional Details

_No response_

**Comment by enocom** [comment] 2023-03-14 21:40
Have you tried this on v2?

**Comment by joseph-maddox** [comment] 2023-03-14 22:44
@enocom I just tested on v2 and it appears to actually override the port-binding from Docker and work as expected (or more closely to what is expected: connecting the the Cloud SQL instance). Not sure why it is able to hijack a port-binding from Docker but that's probably a matter for Docker not Cloud SQL Proxy. Thanks for pointing me to the existence of v2.

**Comment by enocom** [comment] 2023-03-16 16:54
That's encouraging. We'll investigate what's going on with the v1 Proxy in the meantime. Either way, we strongly recommend upgrading to v2 -- it has better stability, a more configurable CLI interface, and support for metrics/tracing/Prometheus.

**Comment by enocom** [comment] 2023-05-11 19:01
I can't reproduce this. Here's what I did. First in one shell:
```
nc -l 127.0.0.1 3306
```

And then in another shell:

```
./cloud_sql_proxy -instances <INSTANCE_CONNECTION_NAME>=tcp:3306
2023/05/11 12:58:17 current FDs rlimit set to 61440, wanted limit is 8500. Nothing to do here.
2023/05/11 12:58:18 listen tcp 127.0.0.1:3306: bind: address already in use
```

Since you're working with v2, I'm going to close this. If for whatever reason you still need v1, let's talk further here.

**Closed by enocom** 2023-05-11 19:01 UTC
Labels: priority: p2, type: bug
