### ISSUE TITLE
Connecting from local machine to Cloud SQL instance with internal IP through cloud-sql-proxy deployed on GKE using IAM auth

### ISSUE THREAD

**Issue by jacek-jablonski** [GoogleCloudPlatform/cloud-sql-proxy#1819] opened 2023-05-30 13:46 UTC
### Question

I'm trying to connect to Cloud SQL with private IP from local machine using IAM auth, but I don't know if this scenario is possible.
I've deployed cloud-sql-proxy on GKE cluster and enabled traffic through TCP load balancer. sql-proxy is started with the following parameters:
```
./cloud-sql-proxy 'redacted:europe-west4:stats-db' --private-ip --address=0.0.0.0 --structured-logs --auto-iam-authn
```
Pod has a configured workload identity using dedicated service account.

I can successfully connect using built-in postgres user credentials, but I cannot connect using IAM auth, f.e.:
```
PGPASSWORD=$(gcloud sql generate-login-token) psql --host=myhost --username=jacek.jablonski@redacted --dbname=stats_db
psql: error: connection to server at "myhost" (10.190.16.101), port 5432 failed: FATAL:  password authentication failed for user "jacek.jablonski@redacted"
```
Is such a connection scenario even possible? If so, what am I possibly doing wrong?

### Additional Details

I'm using the newest version of cloud-sql-proxy 2.3.0.

**Comment by jackwotherspoon** [comment] 2023-05-30 14:06
Hi @jacek-jablonski! Thanks for raising a question for the Cloud SQL Auth Proxy 😄 

Let's see if I can help you get to the bottom of your issue.

There are a few things I notice with your setup:

1. It seems there may be confusion between [Automatic IAM database authentication](https://cloud.google.com/sql/docs/postgres/iam-logins#log-in-with-automatic) (using the `--auto-iam-authn` with the Proxy) and [manual IAM database authentication](https://cloud.google.com/sql/docs/postgres/iam-logins#logging-in-as-a-user) (logging in with password set to oauth2 credentials token). You are invoking the Proxy with automatic IAM authn but then you are attempting to login with manual IAM authn through `PGPASSWORD=$(gcloud sql generate-login-token)`. You do not need to set `PGPASSWORD` when using automatic IAM Authn.
2. **When using a Cloud SQL connector or the Proxy with automatic IAM database authentication, the IAM account that you use to start (invoke) the Proxy must be the same account that authenticates the database.** 
 
What this means is whatever IAM principal is being used in your GKE cluster environment (service account used for GKE or WIF service account) is the only IAM principal that will be allowed to connect via automatic IAM authn. So my guess would bet that `jacek.jablonski@redacted` is not the same IAM principal and credentials that your GKE cluster is using?

@enocom or @hessjcg  may be able to provide a bit more insight into this scenario as well as they are more familiar with using the Proxy in GKE environments

**Comment by jacek-jablonski** [comment] 2023-06-07 16:10
> @jacek-jablonski Did you get the connection working?

I got the connection working only with non-IAM users or with single IAM user same as on proxy's workload identity.

**Comment by enocom** [comment] 2023-06-07 16:37
> with single IAM user same as on proxy's workload identity.

That's working as intended, in that case. The Proxy's workload identity is the IAM user, and so you're doing it right by using the same user.

I'll close this, but if there's anything else we can help with, feel free to re-open with more information.

**Closed by enocom** 2023-06-07 16:37 UTC
Labels: type: question
