### ISSUE TITLE
Better support for running as a daemon process

### ISSUE THREAD

**Issue by sughodke** [GoogleCloudPlatform/cloud-sql-proxy#234] opened 2018-12-18 17:31 UTC
I'm trying to run cloud_sql_proxy in a Google Colab notebook. We can authenticate and the proxy is actually running.
```
!./cloud_sql_proxy --instances=my-project:my-region:my-instance
```

However the notebook will not let me execute other cells, as the cloud_sql_proxy command does not terminate. I would hope that if we send the task to background, the notebook will continue processing.

Note that adding a `&` to run in the background doesn't seem to work in the notebook. The process continues to run foreground.

Please see https://stackoverflow.com/a/49142801 for a complete example.

**Comment by dhduvall** [comment] 2021-02-10 01:29
I added this as a comment to the Stackoverflow question, but a workaround that might be simpler than `screen` is [daemonize](https://software.clapper.org/daemonize/). It should be sufficient for this use case, although not for #290.

**Comment by enocom** [comment] 2021-02-10 18:19
As @dhduvall notes in #290, this now also includes 

> making sure that systemd doesn't mark the proxy service as online until the proxy is ready to take requests

**Comment by enocom** [comment] 2023-03-17 01:55
Partially a duplicate of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1567, which we'll be addressing soon.

For Colab Notebook support, see the Python connector which will be the best option: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector (there's a badge that will take you straight to an example).

**Closed by enocom** 2023-03-17 01:55 UTC
Labels: priority: p3, type: feature request
