### ISSUE TITLE
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0

### ISSUE THREAD

**Issue by wi1dcard** [GoogleCloudPlatform/cloud-sql-proxy#1368] opened 2022-09-01 02:45 UTC
## Bug Description

Recently GCP Cloud SQL (MySQL) scheduled a regular maintenance. After the scheduled maintenance, we can't connect our instances with the Cloud SQL Proxy flag `-enable_iam_login`, even with the `root` user which is not managed by IAM.

The MySQL client output (I'm sure the password is correct and it is reproducible whether the password is):

```
$ mysql -h127.0.0.1 -uroot -P3310 -p
Enter password:
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0
```

Once we remove the `-enable_iam_login` flag, it works but we lose the IAM authentication feature. Therefore, I assume there might be a bug between some underhood changes of this maintenance and the Cloud SQL Proxy IAM login feature.

My expected behavior is that we can still connect to the instance with `-enable_iam_login`, just like before.

## How to reproduce

```
cloud_sql_proxy -enable_iam_login -instances <REDACTED>
# and another terminal:
mysql -h127.0.0.1 -uroot -p
```

## Environment

1. OS type and version: macOS (thinking it might be irrelevant)
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): `1.28.1+darwin.arm64`
3. MySQL client version (`mysql -V`): `mysql  Ver 8.0.30 for macos12.4 on arm64 (Homebrew)`

**Comment by wi1dcard** [comment] 2022-09-01 02:46
cc my team they are also curious @freehere107

**Comment by enocom** [comment] 2022-09-01 15:28
Thanks for the report @wi1dcard. Indeed, there's a backend change that is causing this issue. The team is aware of it and is working on a fix.

Right now Auto IAM AuthN for MySQL isn't supported. Are you launching the proxy for MySQL and Postgres instances? If so, I'm afraid you'll need to use two separate instances on v1. If you're interested in trying the public preview of v2, we support enabling IAM AuthN on a per instance basis, like so:

```
cloud-sql-proxy "<INSTANCE_1>?auto-iam-authn=true" <INSTANCE_2>
```

If you're using manual IAM AuthN (where you supply the OAuth2 token), then there's no need to enable the `enable_iam_login` (v1) or `auth-iam-authn` (v2) flag.

Duplicate of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1318.

**Closed** 2022-09-01 16:58 UTC
Labels: priority: p1, type: question

**Comment by tcnghia** [comment] 2022-09-07 00:09
Do we have a container image for V2?

**Comment by enocom** [comment] 2022-09-07 03:13
Yes: https://github.com/GoogleCloudPlatform/cloud-sql-proxy#container-images.

**Comment by tcnghia** [comment] 2022-09-07 03:36
Thanks @enocom! What tag should I used for V2? I've tried several without success

```
❯ docker pull gcr.io/cloud-sql-connectors/auth-proxy:v2.0.0-preview.0

Error response from daemon: pull access denied for gcr.io/cloud-sql-connectors/auth-proxy, repository does not exist or may require 'docker login': denied: Permission denied for "v2.0.0-preview.0" from request "/v2/cloud-sql-connectors/auth-proxy/manifests/v2.0.0-preview.0".

❯ docker pull gcr.io/cloud-sql-connectors/auth-proxy:v2.0.0.preview.0

Error response from daemon: pull access denied for gcr.io/cloud-sql-connectors/auth-proxy, repository does not exist or may require 'docker login': denied: Permission denied for "v2.0.0.preview.0" from request "/v2/cloud-sql-connectors/auth-proxy/manifests/v2.0.0.preview.0".

❯ docker pull gcr.io/cloud-sql-connectors/auth-proxy:v2.0.0          
Error response from daemon: pull access denied for gcr.io/cloud-sql-connectors/auth-proxy, repository does not exist or may require 'docker login': denied: Permission denied for "v2.0.0" from request "/v2/cloud-sql-connectors/auth-proxy/manifests/v2.0.0".
```

**Comment by enocom** [comment] 2022-09-07 04:05
Sorry about that. I realize I hadn't added flipped the repo the public and the README isn't quite right. :man_facepalming:

Should be fixed now:

```
docker pull gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:2.0.0-preview.0 # no v in the version
# or
docker pull gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:latest
```

If you still have trouble finding those, feel free to file an issue and I'll fix whatever remaining issues there might be. And I'll update the README.

**Comment by tcnghia** [comment] 2022-09-07 04:34
@enocom thanks. I still couldn't access those images.

```
❯ docker pull gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:latest

Error response from daemon: manifest for gcr.io/cloud-sql-connectors/cloud-sql-auth-proxy:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/cloud-sql-connectors/cloud-sql-auth-proxy/manifests/latest".

❯ docker pull gcr.io/cloud-sql-connectors/auth-proxy:latest 

Error response from daemon: manifest for gcr.io/cloud-sql-connectors/auth-proxy:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/cloud-sql-connectors/auth-proxy/manifests/latest".
```

I filed https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1380 as suggested.
