### ISSUE TITLE
The /readiness healthcheck causes MySQL servers to log excessive info and warning messages  

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy#1652] opened 2023-02-13 20:24 UTC
## Bug Description

The /readiness health check determines if the proxy can initiate a TCP connection to each Cloud SQL 
database instance. It opens a TCP connection and then immediately hangs up. This is an effective probe
for network connectivity.

However the database servers do not expect this kind of behavior from a client. The server considers this kind
of a connection an anomaly, and writes a log message. 

MySQL sever writes the following error log message whenever the proxy attempts a /readiness check:

```
INFO [Note] [MY-010914] [Server] Got an error reading communication packets
```

When the mysql server has Query Insights enabled, the Query Insights module will also log this message: 

```
WARNING  [Warning] [MY-000000] [Server] Failed to capture username for connection: 274738 error: 1158
```

This can be a nuisance for any administrator trying to alert on real anomalies in the logs. 

In their default configuration, MSSQL and PGSQL do not produce log messages on a /readiness check.

**Comment by enocom** [comment] 2023-03-15 20:23
The backend team has fixed the warning message. Since we have just INFO messages, I think this is less important.

**Comment by enocom** [comment] 2023-03-17 01:58
It might be better to remove the instance dialing from the healthchecks and instead let users configure health checks against their database separately. For example, for MySQL see https://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready.

**Comment by Swahjak** [comment] 2023-06-14 09:22
Does this also happen for liveness? We're also seeing a lot of  "Got an error reading communication packets" in the server logs, which is potentially causing us to miss 'actual' errors.

**Comment by enocom** [comment] 2023-06-14 15:00
No, only for readiness.

Liveness is purely a "is it alive" check. See https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/internal/healthcheck/healthcheck.go#L160-L163.

**Comment by enocom** [comment] 2023-06-14 15:01
Are you using a readiness check at all?

**Comment by Swahjak** [comment] 2023-06-14 15:21
@enocom thanks for the response, as you have seen I've opened a separate issue https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1840. Unless these issues are related I think we should continue the conversation there.

**Comment by enocom** [comment] 2024-01-23 02:39
Duplicate of #2083 which will resolve this.

**Closed by enocom** 2024-01-23 02:39 UTC
Labels: priority: p3, type: bug
