### ISSUE TITLE
enable_iam_login causing bad handshake

### ISSUE THREAD

**Issue by sl0wik** [GoogleCloudPlatform/cloud-sql-proxy#1436] opened 2022-09-23 20:39 UTC
## Bug Description

MySQL 5.7 started throwing "Bad handshake" error if `-enable_iam_login` flag is specified. This likely happened recently and if it gets into production instances (like App Engine) it will cause a massive problem.

## How to reproduce

  1. Start proxy connection to MySQL 5.7 with flag `-enable_iam_login`
  2. Try to connect using MySQL client - you would get "Bad handshake" (Sequel Ace or PHP) or  "ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 102" (`mysql` command), 

## Environment

1. OS type and version: macOS or docker
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): Cloud SQL Auth proxy: 1.32.0+darwin.amd64

**Comment by enocom** [comment] 2022-09-23 21:10
Thanks for the report @sl0wik. Presently MySQL does not support Auto IAM AuthN. So if you're connecting to only MySQL instances, you can just remove that flag. If you're connecting to a mix of Postgres and MySQL instances and you're relying on Auto IAM AuthN for Postgres, you'll need to either run a second version of the v1 proxy, or upgrade to the v2 proxy (which supports configuring IAM AuthN on a per instance basis).

Duplicate of #1318.

**Closed by enocom** 2022-09-23 21:10 UTC
Labels: type: bug

**Comment by sl0wik** [comment] 2022-09-23 23:11
MySQL does support IAM authentication, and App Engine is running with `enable_iam_login`. I know dozens of production instances running password-less authentication using IAM on App Engine so I'm positive about this. 

Official docs on using IAM authentication with MySQL:
- https://cloud.google.com/sql/docs/mysql/create-edit-iam-instances
- https://cloud.google.com/sql/docs/mysql/add-manage-iam-users#creating-a-database-user

Code example:
https://github.com/firevel/firevel/pull/34

**Comment by sl0wik** [comment] 2022-09-24 14:25
Resolved. Logging in as IAM users to MySQL using access tokens doesn't require `enable_iam_login` flag anymore. It works by default.

Thanks @enocom

**Comment by enocom** [comment] 2022-09-26 15:15
Glad it's working you now. I think you're talking about manual IAM authentication where you have to manually supply the access token (as you're doing in the linked PR). Automatic IAM Authentication is a feature that requires the proxy where supply the user name of an IAM user and the proxy inserts the OAuth2 token in the login request (in addition to refreshing that token).

Beware in the manual IAM authentication approach, it's up to you to get a refreshed token. Otherwise, new connections will fail on an expired token.
