### ISSUE TITLE
pgx query cancel not working with proxy

### ISSUE THREAD

**Issue by anhpngt** [GoogleCloudPlatform/cloud-sql-proxy#1517] opened 2022-10-31 03:32 UTC
## Bug Description

When a query is canceled, the [cancel request from pgx](https://github.com/jackc/pgconn/blob/master/pgconn.go#L904) is sent but not properly received/processed in the Cloud SQL server.

- This happens when I use `pgx` driver with this proxy, not sure about other drivers
- Without the proxy (e.g using IP), then the cancel request works normally

## Example code (or command)
I wrote a piece of code using `pgconn` (the low level api in `pgx`), but the same issue happened with `pgxpool.Pool`.

<details>
  <summary>Demo code</summary>

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"time"

	"github.com/jackc/pgconn"
	"github.com/pkg/errors"
)

var (
	dbuser     = "postgres"
	dbpassword = "postgres"
	dbhost     = "localhost"
	dbport     = "5432"
	dbname     = "tuananh"
)

func init() {
	if os.Getenv("PGUSER") != "" {
		dbuser = os.Getenv("PGUSER")
	}
	if os.Getenv("PGPASSWORD") != "" {
		dbpassword = os.Getenv("PGPASSWORD")
	}
	if os.Getenv("PGHOST") != "" {
		dbhost = os.Getenv("PGHOST")
	}
	if os.Getenv("PGPORT") != "" {
		dbport = os.Getenv("PGPORT")
	}
	if os.Getenv("PGDATABASE") != "" {
		dbname = os.Getenv("PGDATABASE")
	}

	log.Printf("db connection string: postgres://%s:%s@%s:%s/%s?sslmode=disable", dbuser, dbpassword, dbhost, dbport, dbname)
}

func main() {
	conn, err := connectDB()
	if err != nil {
		panic(err)
	}

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()

	ctx1, cancel1 := context.WithTimeout(ctx, time.Second*10)
	defer cancel1()
	go func() {
		defer cancel1()
		query(ctx1, conn)
	}()

	time.Sleep(time.Second * 2) // sleep for 2s to prevent cancel running before query
	ctx2, cancel2 := context.WithTimeout(ctx, time.Second*5)
	defer cancel2()
	go func() {
		defer cancel2()
		cancelquery(ctx2, conn)
	}()

	<-ctx1.Done()
	<-ctx2.Done()
	log.Printf("all processes finished. Ctrl+C to exit")
	<-ctx.Done()
}

func connectDB() (*pgconn.PgConn, error) {
	connStr := fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable", dbuser, dbpassword, dbhost, dbport, dbname)
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()
	conn, err := pgconn.Connect(ctx, connStr)
	if err != nil {
		return nil, errors.Wrap(err, "pgxpool.ConnectConfig")
	}
	return conn, nil
}

// query runs some innocuous SELECT statement
func query(ctx context.Context, conn *pgconn.PgConn) {
	log.Println("[1] start sleeping")
	mrr := conn.Exec(ctx, "SELECT pg_sleep(60);")
	for mrr.NextResult() {
		_, _ = mrr.ResultReader().Close()
	}
	if err := mrr.Close(); err != nil { // mrr.Close() gets the first error while reading result
		log.Printf("[1] query failed: %s", err)
	}

	log.Println("[1] query finished")
}

func cancelquery(ctx context.Context, conn *pgconn.PgConn) {
	log.Println("[2] canceling query")
	err := conn.CancelRequest(ctx)
	if err != nil {
		log.Printf("[2] failed to cancel request: %s", err)
	}
	log.Println("[2] done canceling query")
}
```
</details>

Output
```sh
$ PGUSER=myIAMUser PGPORT=5432 PGDATABASE=mydb go run requestcancel/main.go 
2022/10/31 10:33:40 db connection string: postgres://myIAMUser:postgres@localhost:5432/mydb?sslmode=disable
2022/10/31 10:33:41 [1] start sleeping
2022/10/31 10:33:43 [2] canceling query
2022/10/31 10:33:43 [2] done canceling query
2022/10/31 10:33:51 [1] query failed: timeout: context deadline exceeded
2022/10/31 10:33:51 [1] query finished
2022/10/31 10:33:51 all processes finished. Ctrl+C to exit
^C

# but when checking inside the server, the connection is still running
(psql)
mydb=> select pid, state, query from pg_stat_activity where datname='mydb' and usename='myIAMUser';
   pid   | state  |        query         
---------+--------+----------------------
 1582790 | active | SELECT pg_sleep(60);
(1 row)

```

## How to reproduce

  1. Run `cloud_sql_proxy`
  2. Run the script above to connect & use the proxy (with your appropriate `PG*` env vars)

## Environment

1. OS type and version: `Linux anhpngt-manabie 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): `Cloud SQL Auth proxy: 1.33.0+linux.amd64
`

I also had a quick test with [cloud-sql-go-connector](https://github.com/googlecloudplatform/cloud-sql-go-connector), but it had the same problem.

**Comment by anhpngt** [comment] 2022-10-31 03:57
Output of a run without using the proxy (using private IP instead). Note that the error from `[1]` now is `due to user request`

```sh
root@ubuntu-tuananh:/# PGHOST=10.111.7.5 PGUSER=postgres PGPASSWORD=mypassword PGDATABASE=mydb ./main 
2022/10/31 10:55:21 db connection string: postgres://postgres:mypassword@10.111.7.5:5432/mydb?sslmode=disable
2022/10/31 10:55:21 [1] start sleeping
2022/10/31 10:55:23 [2] canceling query
2022/10/31 10:55:23 [1] query failed: ERROR: canceling statement due to user request (SQLSTATE 57014)
2022/10/31 10:55:23 [1] query finished
2022/10/31 10:55:23 [2] done canceling query
2022/10/31 10:55:23 all processes finished. Ctrl+C to exit
^C
```

**Comment by enocom** [comment] 2022-10-31 13:00
Thanks for the detailed report. I’ll look this morning.

**Comment by enocom** [comment] 2022-10-31 14:21
Related: https://pkg.go.dev/github.com/jackc/pgconn#PgConn.CancelRequest

**Comment by enocom** [comment] 2022-10-31 20:15
In general, though, the proxy has no knowledge of the postgres protocol and just copies bytes back and forth between the client and the remote proxy server. So even if there were a bug here, it would probably be in pgconn or possibly in the proxy server.

Also, note that pgconn isn't safe for concurrent use. (See [here](https://pkg.go.dev/github.com/jackc/pgconn#PgConn)).

Would you mind showing me how you're running this experiment with pgxpool?

**Comment by anhpngt** [comment] 2022-11-01 02:55
Hi, thanks for the quick response!

Here's my sample code using pgxpool

<details>
  <summary>Sample code</summary>

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"sync"
	"time"

	"github.com/jackc/pgx/v4/pgxpool"
	"github.com/pkg/errors"
)

var (
	dbuser     = "postgres"
	dbpassword = "postgres"
	dbhost     = "localhost"
	dbport     = "5432"
	dbname     = "tuananh"

	initDB sync.Once
)

func init() {
	if os.Getenv("PGUSER") != "" {
		dbuser = os.Getenv("PGUSER")
	}
	if os.Getenv("PGPASSWORD") != "" {
		dbpassword = os.Getenv("PGPASSWORD")
	}
	if os.Getenv("PGHOST") != "" {
		dbhost = os.Getenv("PGHOST")
	}
	if os.Getenv("PGPORT") != "" {
		dbport = os.Getenv("PGPORT")
	}
	if os.Getenv("PGDATABASE") != "" {
		dbname = os.Getenv("PGDATABASE")
	}

	log.Printf("db connection string: postgres://%s:%s@%s:%s/%s?sslmode=disable", dbuser, dbpassword, dbhost, dbport, dbname)
}

func main() {
	insertDuration := time.Second * 10
	lockTableDuration := insertDuration + time.Second*3
	statisticDuration := lockTableDuration + time.Second*3

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()

	// one goroutine to count connections
	statCtx, statCancel := context.WithTimeout(ctx, statisticDuration)
	defer statCancel()
	go printStatistics(statCtx)

	// one goroutine to lock table
	lockCtx, lockCancel := context.WithTimeout(ctx, lockTableDuration)
	defer lockCancel()
	go lockTable(lockCtx)

	// finally, run some inserts
	// there's a chance this insert is run before table is locked, so we sleep for 1 sec
	time.Sleep(time.Second)
	insertCtx, insertCancel := context.WithTimeout(ctx, insertDuration)
	defer insertCancel()
	insertIntoDB(insertCtx)

	// wait for all contexts before exiting
	<-insertCtx.Done()
	<-lockCtx.Done()
	<-statCtx.Done()
}

func connectDB() (*pgxpool.Pool, error) {
	connStr := fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable", dbuser, dbpassword, dbhost, dbport, dbname)
	poolCfg, err := pgxpool.ParseConfig(connStr)
	if err != nil {
		return nil, errors.Wrap(err, "pgxpool.ParseConfig")
	}

	poolCfg.MaxConns = 8
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()
	pool, err := pgxpool.ConnectConfig(ctx, poolCfg)
	if err != nil {
		return nil, errors.Wrap(err, "pgxpool.ConnectConfig")
	}

	// init once
	initDB.Do(func() {
		if _, err := pool.Exec(ctx, "CREATE TABLE IF NOT EXISTS t(id SERIAL PRIMARY KEY, content TEXT);"); err != nil {
			panic(errors.Wrap(err, "failed to init db"))
		}
	})
	return pool, nil
}

// lockTable locks table t. After ctx is done, it will release the lock.
func lockTable(ctx context.Context) {
	db, err := connectDB()
	if err != nil {
		panic(errors.Wrap(err, "connectDB in lockTable"))
	}

	log.Printf("[2] start locking table")
	tx, err := db.Begin(ctx)
	if err != nil {
		panic(errors.Wrap(err, "db.Begin"))
	}
	if _, err = tx.Exec(ctx, "LOCK TABLE t IN EXCLUSIVE MODE;"); err != nil {
		cancelCtx, cancel := context.WithTimeout(context.Background(), time.Second*10)
		defer cancel()
		_ = tx.Rollback(cancelCtx)
		panic(errors.Wrap(err, "tx.Exec lock table"))
	}
	// wait until timeout then unlock table
	// not really good code here since the program may exit before having a chance to clean up
	<-ctx.Done()
	cancelCtx, cancel := context.WithTimeout(context.Background(), time.Second*10)
	defer cancel()
	_ = tx.Rollback(cancelCtx)
	log.Printf("[2] table lock released")
}

// insertIntoDB runs some innocuous INSERT statements into table t
func insertIntoDB(ctx context.Context) {
	db, err := connectDB()
	if err != nil {
		panic(errors.Wrap(err, "connectDB in insert"))
	}
	log.Printf("[1] start inserting into db")
	_, err = db.Exec(ctx, "INSERT INTO t(content) VALUES('random')")
	if err != nil {
		log.Printf("failed to insert data")
	}
	log.Printf("[1] inserting finished")
}

// printStatistics prints the number of INSERT-related connections used every 1 sec
func printStatistics(ctx context.Context) {
	db, err := connectDB()
	if err != nil {
		panic(err)
	}
	for {
		select {
		case <-ctx.Done():
			return
		default:
			var c int
			err := db.QueryRow(ctx, "SELECT count(1) FROM pg_stat_activity WHERE datname = $1 AND state = 'active' AND query LIKE 'INSERT INTO%'", dbname).Scan(&c)
			if err != nil {
				log.Printf("stats: failed to count connection: %s", err)
			} else {
				log.Printf("stats: insert connection count: %d", c)
			}
			time.Sleep(time.Second)
		}
	}
}
```

</details>

**Comment by anhpngt** [comment] 2022-11-01 03:10
for the background, this is an issue we've just had:
- a query locked a table, causing lots of other query to be timed out
- timed out queries' connections are not properly released (not until table is unlocked), thus causing a connection spike reaching the connection limit number
- as a result, no other services can connect to the db anymore (out of connections)

though i'm not quite sure it's supposed to be fixed from pgx's side or here :thinking:

**Comment by anhpngt** [comment] 2022-11-04 18:12
hi @enocom, me and my colleague found out that `cloud_sql_proxy` v2 (commit https://github.com/GoogleCloudPlatform/cloud-sql-proxy/commit/dd04a83019758f3b470f4ce090ad4c112501efbf to be specific) does not have this bug, but only when using user:pass, not IAM auth

hope that helps with your debugging somewhat

**Comment by enocom** [comment] 2022-11-04 18:25
That's interesting and makes me think it's a proxy server issue. Thanks for the update. I'll work this today.

**Comment by enocom** [comment] 2022-11-04 19:43
After doing some investigation, here's what I found:

I wrote a minimal reproduction (below) that starts a long running query, waits for a SIGTERM, and then cancels the query. This is what I did:

1. I start the minimal reproduction
2. Confirm the long running query is running in the database with `select pid, state, query from pg_stat_activity;`
3. Send a SIGTERM to the minimal reproduction
4. Check if the query is still running.

For both v1 and v2:

1. Using standard DB AuthN, the call to cancel the query **succeeds**.
5. Using Auto IAM AuthN, the call to cancel the query **fails**.

Minimal Reproduction:

``` golang
package main

import (
        "context"
        "fmt"
        "log"
        "os"
        "os/signal"

        "github.com/jackc/pgconn"
)

func main() {
        var (
                dbhost = "localhost"
                dbport = "5432"

                dbuser     = "postgres"
                dbpassword = "postgres"
                dbname     = "postgres"
        )

        // Make a channel listening for SIGTERM
        c := make(chan os.Signal, 1)
        signal.Notify(c, os.Interrupt)

        ctx := context.Background()

        dsn := fmt.Sprintf(
                "postgres://%s:%s@%s:%s/%s?sslmode=disable",
                dbuser, dbpassword, dbhost, dbport, dbname,
        )
        conn, err := pgconn.Connect(ctx, dsn)
        if err != nil {
                log.Fatal(err)
        }

        log.Println("starting long running query")

        // Start a long running query
        conn.Exec(ctx, "SELECT pg_sleep(60);")

        <-c
        log.Println("SIGTERM received; canceling query")

        // Now cancel that query
        err = conn.CancelRequest(ctx)
        if err != nil {
                log.Fatal(err)
        }
        log.Println("query canceled")
}
```

**Comment by enocom** [comment] 2022-11-04 20:11
I'm half thinking this might be a simple permissions problem where the IAM user does not have the permission to cancel a process.

**Comment by enocom** [comment] 2022-11-04 21:30
If I user manual IAM authentication (where I provide the IAM user name and the user's OAuth2 token), the query cancellation also works. So this seems to be an issue just with Auto IAM Authentication.

**Comment by enocom** [comment] 2022-11-04 21:36
When I use connect to my Cloud SQL using using psql and the Proxy with Auto IAM AuthN on, and issue a `select pg_cancel_backend(<PID>);` the cancellation works.

**Comment by nvcnvn** [comment] 2022-11-07 04:42
Btw is it a public issue tracking that we can follow @enocom ?

**Comment by enocom** [comment] 2022-11-07 13:35
This would be it. 🤓

**Comment by enocom** [comment] 2022-11-10 22:56
Quick update: I've shared this with the backend team and they're investigating.

**Comment by nvcnvn** [comment] 2022-11-23 02:25
@enocom sorry for bothering you but can you have any estimate when this issue can be confirm and resolve.
We are considering to roll back to use password auth. Not sure if any other workaround for this case?

**Comment by enocom** [comment] 2022-11-23 15:55
It's not as elegant but `pg_cancel_backend` works here.

There's a production freeze in place right now, so any fix would probably still be a ways off. I'll update here when there's more to know.

**Comment by enocom** [comment] 2023-01-11 20:56
Haven't forgotten about this. The backend team will be fixing this. I'll update here when there's an ETA.

**Comment by danmcgee-soda** [comment] 2023-03-21 18:31
Wanted to add bit more information that we discovered after investigating this issue today, and stumbling into this bug report.

* The workaround of password-based auth also works with v1.27.0
* This is fully reproducible with psql, eliminating pgx or other libraries completely

Using `cloud_sql_proxy -dir=/tmp -instances <instance>`, canceling works fine:
```
% psql -h /tmp/your-socket-path -U default merchant
Password for user default: 
psql (14.7 (Homebrew), server 14.4)
merchant=> select pg_sleep(15);
^CCancel request sent
ERROR:  canceling statement due to user request
```

But adding the `-enable_iam_login` flag, e.g. `cloud_sql_proxy -dir=/tmp -instances <instance> -enable_iam_login` breaks it:
```
% psql -h /tmp/our-socket-path -U default merchant
Password for user default: 
psql (14.7 (Homebrew), server 14.4)
merchant=> select pg_sleep(15);
^CCancel request sent
^CCancel request sent
^CCancel request sent
```

I tried cancelling three times this second case, and none were successful at getting through.

Another important bit - I actually used username/password auth in both cases- the determining factor is not actually which type of auth you USE, but only whether automatic IAM authentication is enabled.

**Comment by enocom** [comment] 2023-03-24 15:21
A fix has been merged and will be rolling out soon. I'll update here when I have more informatin.

**Comment by danmcgee-soda** [comment] 2023-04-19 13:52
> A fix has been merged and will be rolling out soon. I'll update here when I have more information.

I was wondering if you had any updates available? I didn't see anything in the most recent [PostgreSQL Cloud SQL release notes](https://cloud.google.com/sql/docs/postgres/release-notes) alluding to a fix for this, but maybe it is included? I also wasn't sure if this was on the GCP side, or the proxy/golang library side.

**Comment by enocom** [comment] 2023-04-19 15:27
Sorry this slipped off my radar. Yes, the issue has been fixed. Thanks for the reminder.

**Closed by enocom** 2023-04-19 15:27 UTC
Labels: priority: p2, type: bug

**Comment by enocom** [comment] 2023-04-19 16:39
A little more information: if you have a custom maintenance window, you'll need to apply the update. Otherwise, the rollout it done.
