### ISSUE TITLE
Support socket activation with systemd and launchd

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/cloud-sql-proxy#1596] opened 2022-12-27 15:18 UTC
## Feature Description

It would be convenient to support socket activation for Cloud SQL, for use cases like running locally. While the proxy is lightweight enough to run all the time, it does need to periodically refresh certificates, so it would be nice to implement socket activation, so that systemd or launchd can start the proxy.

## Alternatives Considered

*Are there any workaround or third party tools to replicate this behavior? Why would adding this feature be preferred over them?*

No, not that I'm aware of - this is a feature that needs to be added to code, but it looks pretty straightforward (the code needs to detect that socket activation happened, and use the file descriptors passed from the init system instead of creating new listeners)

## Additional Context
Please reference any other issues, PRs, descriptions, or screenshots here.

* CoreOS' [go-systemd library has some helper functions to handle this](https://github.com/coreos/go-systemd/blob/main/activation/files_unix.go), and the process seems straightforward enough using core Go functions (`net.FileListener(f)` on a File using a file descriptor from `os.NewFile(uintptr(fd), name)`
* ghostunnel has [documentation for socket activation using systemd and launchd](https://github.com/ghostunnel/ghostunnel/blob/master/docs/SOCKET-ACTIVATION.md). The [launchd implementation](https://github.com/ghostunnel/ghostunnel/blob/f71137b46c6aab933c0cdb2e9797a95d30bfdb73/socket/launchd_enabled.go) unfortunately requires cgo, as it needs to invoke [`launch_activate_socket` to get a list of file descriptors](https://developer.apple.com/documentation/xpc/1505523-launch_activate_socket). I'm not sure if there's a more portable way to do this.

**Comment by kurtisvg** [comment] 2022-12-27 23:02
One workaround might be FUSE mode -- but would only work for unix socket connections. This method would have the advantage of working for TCP connections.

**Comment by enocom** [comment] 2023-01-10 23:06
What's the relationship between this issue and https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1567? I don't know a lot about systemd.

**Comment by enocom** [comment] 2023-03-17 01:56
I'm going to treat this as a duplicate of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1567. Feel free to add more details there.

**Closed by enocom** 2023-03-17 01:56 UTC
Labels: priority: p1, type: feature request
